name = "aba-monitor-bot"
main = "src/index.ts"
compatibility_date = "2024-03-20"

# KV Namespace for caching docs context and query limits
[[kv_namespaces]]
binding = "CACHE"
id = "187f2a27bd2d47d98197b2ad891f21d2"

